# Generated by Django 3.0.3 on 2020-03-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('yaurl', '0002_auto_20200306_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortedurl',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='created_at'),
        ),
    ]
