# Generated by Django 3.0.3 on 2020-03-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('yaurl', '0003_auto_20200307_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortedurl',
            name='created_at',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='shortedurl',
            name='original_url',
            field=models.CharField(max_length=512, verbose_name='Original URL'),
        ),
        migrations.AlterField(
            model_name='shortedurl',
            name='redirects',
            field=models.IntegerField(default=0, verbose_name='Redirects'),
        ),
        migrations.AlterField(
            model_name='shortedurl',
            name='shorted_id',
            field=models.CharField(max_length=64, verbose_name='Shorted ID'),
        ),
    ]
