# Generated by Django 3.0.3 on 2020-03-07 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('yaurl', '0004_auto_20200307_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortedurl',
            name='shorted_id',
        ),
    ]
